name: Java CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        distribution: 'temurin' # 使用するJDKのディストリビューション
        java-version: '21'    # 使用するJavaのバージョン

    - name: Compile Java file
      run: javac Test.java

    - name: Run Java program
      run: java Test
