name: Java CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # 使用するJDKのディストリビューション
        java-version: '21'    # 使用するJavaのバージョン

    - name: Compile Java file
      run: javac *.java

    - name: Run Java program
      run: |
        # Find all compiled class files
        class_files=$(find -name "*.class")

        # Extract class names and convert paths to package names
        for file in $class_files; do
          echo "file name: $file"
          class_name=$(echo $file | sed 's|.class||; s|/||; s|.||')
          echo "Class name: $class_name"

          java $class_name
          if javap -public $class_name | grep 'public static void main' > /dev/null; then
            echo "Found main method in $class_name, running it..."
            java $class_name
            break
          fi
        done
