name: Java CI

on: 
  push:
    paths:
      - '**/*.java'
    branches: [ test ]
  #pull_request:
    #paths:
      #- '**/*.java'
    #branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 2

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # 使用するJDKのディストリビューション
        java-version: '21'    # 使用するJavaのバージョン

    - name: Get list of modified Java files
      id: modified_files
      run: |
        git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep '\.java$' > files.txt
        echo "Modified Java files:"
        cat files.txt

    - name: Compile and run modified Java files
      run: |
        while IFS= read -r file; do
          # Compile the Java file
          javac "$file"
          #echo "javac file: $file"

          # Extract the class name from the file path
          class_name=$(echo "$file" | sed 's|.java||;')
          #echo "class_name: $class_name"

          # Check if the class contains the main method
          if javap -public $class_name | grep 'public static void main' > /dev/null; then
            echo "Found main method in $class_name, running it..."
            java $class_name
          else
            echo "Not found main method in $class_name"
          fi

          echo
        done < files.txt





    #- name: Compile Java file
      #run: javac *.java

    #- name: Run Java program
      #run: |
        # Find all compiled class files
        #class_files=$(find -name "*.class")

        # Extract class names and convert paths to package names
        #for file in $class_files; do
          #echo "file name: $file"
          #.class,/,.を空文字列にする 
          #class_name=$(echo $file | sed 's|.class||; s|/||; s|.||')
          #echo "Class name: $class_name"

          #java $class_name
          #grep 'public static void main'　見つけた場合、「0」ステータスコードが返され、見つからなかった場合、「1」ステータスコードが返される
          #if javap -public $class_name | grep 'public static void main' > /dev/null; then
            #echo $?
            #echo "Found main method in $class_name, running it..."
            #java $class_name
            #break
          #else
            #echo $?
            #echo "Not Found main method in $class_name."
          #fi

          #echo
        #done
